# API PARKING LOT MANAGEMENT

// get all parking lots

GET {{host-url}}//parking

###

// get parking lot by id

GET {{host-url}}//parking//1

###


# ARDUINO management

// create new parking lot post


###

POST {{host-url}}//parking
Content-Type: application/json

{
  "id": 15,
  "status": 1
}

###

// create new parking lot get

GET {{host-url}}//arduino_get/
Content-Type: application/json

{
  "id": 15,
  "status": 1
}

###


// tests

GET {{host-url}}//arduino_get

###

GET {{host-url}}//arduino_get_p?id=1&status=2

###

// working update status

PUT {{host-url}}//
Content-Type: application/json

{
  "id": 1,
  "number": 2,
  "updatedAt": "1900-01-09T15:43:35.000+0000",
  "status": "UNKNOWN"
}

###

POST {{host-url}}//parking
Content-Type: application/json

{
  "id": 1,
  "number": 2,
  "updatedAt": "2020-01-09T:43:35.000+0000",
  "status": "FREE"
}

###